name: test

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: compose
        run: docker compose -f Compose.yml --env-file .env.test up -d
